myfile:func.cpp func.h main.cpp
	g++ -o myfile func.cpp func.h main.cpp -std=gnu++11
debug:func.cpp func.h main.cpp
	g++ -o debug func.cpp func.h main.cpp -g -std=gnu++11
.PHONY:clean
clean:
	rm -f myfile debug
